<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>StardewValleyToolBridge</AssemblyName>
    <StardewPath Condition="'$(StardewPath)' == ''">$(STARDEW_PATH)</StardewPath>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="StardewModdingAPI" HintPath="$(StardewPath)\StardewModdingAPI.dll" Private="false" />
    <Reference Include="Stardew Valley" HintPath="$(StardewPath)\Stardew Valley.dll" Private="false" />
    <Reference Include="StardewValley.GameData" HintPath="$(StardewPath)\StardewValley.GameData.dll" Private="false" />
    <Reference Include="MonoGame.Framework" HintPath="$(StardewPath)\MonoGame.Framework.dll" Private="false" />
  </ItemGroup>
</Project>
